#!/bin/bash

# Define top-level dir
bind_dir=/storage/research/cinn_comp/ThalSR
# Location of own dir
zan_dir=${bind_dir}/zan

# Set path to krauth-morel nuclei
krauth_path=${bind_dir}/zan/derivatives/thal_nuclei/krauth-morel-nuclei
# Set path to HIPS-THOMAS nuclei
left_hipsthomas_path=${bind_dir}/zan/derivatives/thal_nuclei/space_correction/ants_output/sub-${SLURM_ARRAY_TASK_ID}/hipsthomas/left
right_hipsthomas_path=${bind_dir}/zan/derivatives/thal_nuclei/space_correction/ants_output/sub-${SLURM_ARRAY_TASK_ID}/hipsthomas/right

# Define subjects
subs=${SLURM_ARRAY_TASK_ID}

# This will execute eval.seg. on defined subjects
for sub in ${subs}; do
    for seg1 in "2" "4" "5" "6" "7" "8" "9" "10" "11" "12" ; do
        for seg2 in "2" "4" "5" "6" "7" "8" "9" "10" "11" "12" ; do

            # Get list of left krauth nuclei
            cd ${krauth_path}/left && \
            left_krauth=$(ls left_KM-${seg1}_*.nii.gz) && \
            cd ../../
            # Get list of right krauth nuclei
            cd ${krauth_path}/right && \
            right_krauth=$(ls right_KM-${seg1}_*.nii.gz) && \
            cd ../../

            # Left segmentation
            for krauth in ${left_krauth}; do
        
                # Run for hipsthomas
                mkdir -p ${zan_dir}/derivatives/evalseg_output/sub-${sub}/hipsthomas/left/ && \
                /storage/research/cinn_comp/ThalSR/EvalSegToolbox/EvaluateSegmentation_CentOS /${krauth_path}/left/${krauth} ${left_hipsthomas_path}/sub-${sub}_hipsthomas_left-${seg2}.nii.gz -xml ${zan_dir}/derivatives/evalseg_output/sub-${sub}/hipsthomas/left/sub-${sub}_evalseg_left_KM-${seg1}_T1-${seg2}.xml -use AVGDIST -unit millimeter
            
            done

            # Right segmentation
            for krauth in ${right_krauth}; do
        
                # Run for hipsthomas
                mkdir -p ${zan_dir}/derivatives/evalseg_output/sub-${sub}/hipsthomas/right/ && \
                /storage/research/cinn_comp/ThalSR/EvalSegToolbox/EvaluateSegmentation_CentOS /${krauth_path}/right/${krauth} ${right_hipsthomas_path}/sub-${sub}_hipsthomas_right-${seg2}.nii.gz -xml ${zan_dir}/derivatives/evalseg_output/sub-${sub}/hipsthomas/right/sub-${sub}_evalseg_right_KM-${seg1}_T1-${seg2}.xml -use AVGDIST -unit millimeter

            done
        done
    done
done
