#!/bin/bash

#SBATCH -J ANTSzan
#SBATCH -N 1
#SBATCH --cpus-per-task=16
#SBATCH --mem-per-cpu=4G
#SBATCH --mail-user=sl009034@student.reading.ac.uk
#SBATCH --mail-type=ALL
#SBATCH --array=51,90,204,212,231,237,249,255,285,318,357,370,448
#SBATCH --partition=cinn

### Top-level project directory
# Note: All other paths get defined in relation to this
bind_dir=/storage/research/cinn_comp/ThalSR

### Where does the singularity container live?
simg=/storage/research/cinn_comp/ThalSR/singularityContainers/ants_2.5.1_20240429.simg

### Where should output ROIs be saved?
output_dir=/storage/research/cinn_comp/ThalSR/zan/derivatives/thal_nuclei/space_correction/ants_output
mkdir -m 775 -p ${output_dir} && \
mkdir -m 775 -p ${output_dir}/sub-${SLURM_ARRAY_TASK_ID}/t1thomas/left && \
mkdir -m 775 -p ${output_dir}/sub-${SLURM_ARRAY_TASK_ID}/t1thomas/right

### Define pathing for MNI ROIs
# Where do the source ROIs (in MNI space) live?
source_roi_dir=${bind_dir}/zan/derivatives/thal_nuclei/space_correction/fslmaths_output/sub-${SLURM_ARRAY_TASK_ID}/t1thomas/left

# What MNI ROIs should be warped into T1w space? T1-THOMAS NUCLEI
left_warp_these=(\
  sub-${SLURM_ARRAY_TASK_ID}_t1thomas_left-2.nii.gz\
  sub-${SLURM_ARRAY_TASK_ID}_t1thomas_left-4.nii.gz\
  sub-${SLURM_ARRAY_TASK_ID}_t1thomas_left-5.nii.gz \
  sub-${SLURM_ARRAY_TASK_ID}_t1thomas_left-6.nii.gz \
  sub-${SLURM_ARRAY_TASK_ID}_t1thomas_left-7.nii.gz \
  sub-${SLURM_ARRAY_TASK_ID}_t1thomas_left-8.nii.gz \
  sub-${SLURM_ARRAY_TASK_ID}_t1thomas_left-9.nii.gz \
  sub-${SLURM_ARRAY_TASK_ID}_t1thomas_left-10.nii.gz \
  sub-${SLURM_ARRAY_TASK_ID}_t1thomas_left-11.nii.gz \
  sub-${SLURM_ARRAY_TASK_ID}_t1thomas_left-12.nii.gz
)

right_warp_these=(\
  sub-${SLURM_ARRAY_TASK_ID}_t1thomas_right-2.nii.gz\
  sub-${SLURM_ARRAY_TASK_ID}_t1thomas_right-4.nii.gz\
  sub-${SLURM_ARRAY_TASK_ID}_t1thomas_right-5.nii.gz \
  sub-${SLURM_ARRAY_TASK_ID}_t1thomas_right-6.nii.gz \
  sub-${SLURM_ARRAY_TASK_ID}_t1thomas_right-7.nii.gz \
  sub-${SLURM_ARRAY_TASK_ID}_t1thomas_right-8.nii.gz \
  sub-${SLURM_ARRAY_TASK_ID}_t1thomas_right-9.nii.gz \
  sub-${SLURM_ARRAY_TASK_ID}_t1thomas_right-10.nii.gz \
  sub-${SLURM_ARRAY_TASK_ID}_t1thomas_right-11.nii.gz \
  sub-${SLURM_ARRAY_TASK_ID}_t1thomas_right-12.nii.gz
)

### Define pathing for fmriprep
# Where's the fmriprep top-level directory?
fmriprep_dir=${bind_dir}/zan/derivatives/sing_fmriprep_krauth-morel/fmriprep
# Inside each fmriprep subject folder, where are the anatomical scans?
anat_suffix=sub-${SLURM_ARRAY_TASK_ID}/anat
# What's the name-stem for the T1w anatomical scan?
t1w_suffix=_desc-preproc_T1w.nii.gz
# What's the name-stem for the MNI-to-T1w transform matrix?
trans_file_suffix=_from-T1w_to-MNI152NLin6Asym_mode-image_xfm.h5

### Run ANTs - Remember to change the /left or /right dir in output to desired one
for roi in ${left_warp_these[*]}
do
  singularity exec --bind ${bind_dir} ${simg} \
  antsApplyTransforms \
  -i ${source_roi_dir}/${roi} \
  -r /storage/research/cinn_comp/ThalSR/zurich-atlas/MorelAtlasMNI152/MNI152_T1_1mm.nii.gz \
  -t ["${fmriprep_dir}/${anat_suffix}/sub-${SLURM_ARRAY_TASK_ID}${trans_file_suffix}"] \
  -n NearestNeighbor \
  -o ${output_dir}/sub-${SLURM_ARRAY_TASK_ID}/t1thomas/left/${roi}
done

source_roi_dir=${bind_dir}/zan/derivatives/thal_nuclei/space_correction/fslmaths_output/sub-${SLURM_ARRAY_TASK_ID}/t1thomas/right

for roi in ${right_warp_these[*]}
do
  singularity exec --bind ${bind_dir} ${simg} \
  antsApplyTransforms \
  -i ${source_roi_dir}/${roi} \
  -r /storage/research/cinn_comp/ThalSR/zurich-atlas/MorelAtlasMNI152/MNI152_T1_1mm.nii.gz \
  -t ["${fmriprep_dir}/${anat_suffix}/sub-${SLURM_ARRAY_TASK_ID}${trans_file_suffix}"] \
  -n NearestNeighbor \
  -o ${output_dir}/sub-${SLURM_ARRAY_TASK_ID}/t1thomas/right/${roi}
done