#!/bin/bash

#SBATCH -J fMRIprep
#SBATCH -N 1
#SBATCH --cpus-per-task=16
#SBATCH --mem-per-cpu=4G
#SBATCH --mail-user=sl009034@student.reading.ac.uk
#SBATCH --mail-type=ALL
#SBATCH --array=1,3,5,6,8 #change this as needed
#SBATCH --partition=scavenger
#SBATCH --time=00:05:00 #change as needed

export SINGULARITYENV_TEMPLATEFLOW_HOME=/templateflow

singularity run --cleanenv -B /storage/research/cinn_comp/ThalSR/zan/derivatives/Freesurfer:/Freesurfer -B /storage/research/cinn_comp/ThalSR/templateflow:/templateflow -B /storage/research/cinn_comp/ThalSR/zan/derivatives/sing_prac:/practice -B /storage/research/cinn_comp/ThalSR/singularityContainers:/fmriprep-23.1.4.simg


