#!/bin/bash

#SBATCH -J freesurfer
#SBATCH -N 1
#SBATCH --cpus-per-task=16
#SBATCH --mem-per-cpu=8G
#SBATCH --mail-user=sl009034@student.reading.ac.uk
#SBATCH --mail-type=ALL
#SBATCH --array=0-556
#SBATCH --partition=cinn
