#!/bin/bash
#SBATCH -J ANTSzan
#SBATCH -N 1
#SBATCH --cpus-per-task=16
#SBATCH --mem-per-cpu=4G
#SBATCH --mail-user=sl009034@student.reading.ac.uk
#SBATCH --mail-type=ALL
#SBATCH --array=0
#SBATCH --partition=cinn

### Top-level project directory
# Note: All other paths get defined in relation to this
bind_dir=/storage/research/cinn_comp/ThalSR

### Where does the singularity container live?
simg=/storage/research/cinn_comp/ThalSR/singularityContainers/ants_2.5.1_20240429.simg

### Where should output ROIs be saved?
output_dir=/storage/research/cinn_comp/ThalSR/zan/derivatives/thal_nuclei/space_correction/ants_output
mkdir -m 775 -p ${output_dir}
mkdir -m 775 -p ${output_dir}/sub-0_thomasfull

echo "Made new directories."

### Define pathing for MNI ROIs
# Where do the source ROIs (in MNI space) live? THOMASFULL ONLY!!!
source_roi_dir=${bind_dir}/zan/derivatives/singularity_prep_seg_backup/fmriprep/sub-0/anat/T1-THOMAS/left

# What MNI ROIs should be warped into T1w space? T1-THOMAS NUCLEI
left_warp_these=thomasfull.nii.gz

right_warp_these=thomasrfull.nii.gz

### Define pathing for fmriprep
# Where's the fmriprep top-level directory?
fmriprep_dir=${bind_dir}/zan/derivatives/sing_fmriprep_krauth-morel/fmriprep

# Inside each fmriprep subject folder, where are the anatomical scans?
anat_suffix=sub-0/anat

# What's the name-stem for the T1w anatomical scan?
t1w_suffix=_desc-preproc_T1w.nii.gz

# What's the name-stem for the MNI-to-T1w transform matrix?
trans_file_suffix=_from-T1w_to-MNI152NLin6Asym_mode-image_xfm.h5

echo "Starting ANTS transform."

### Run ANTs - Remember to change the /left or /right dir in output to desired one
for roi in ${left_warp_these[*]}
do
  singularity exec --bind ${bind_dir} ${simg} \
  antsApplyTransforms \
  -i ${source_roi_dir}/${roi} \
  -r ${fmriprep_dir}/${anat_suffix}/sub-0${t1w_suffix} \
  -t ["${fmriprep_dir}/${anat_suffix}/sub-0${trans_file_suffix}"] \
  -n NearestNeighbor \
  -o ${output_dir}/sub-0_thomasfull/sub-0_mni_left_${roi}
done

echo "ANTS transform for left thomasfull complete."

source_roi_dir=${bind_dir}/zan/derivatives/singularity_prep_seg_backup/fmriprep/sub-0/anat/T1-THOMAS/right

for roi in ${right_warp_these[*]}
do
  singularity exec --bind ${bind_dir} ${simg} \
  antsApplyTransforms \
  -i ${source_roi_dir}/${roi} \
  -r ${fmriprep_dir}/${anat_suffix}/sub-0${t1w_suffix} \
  -t ["${fmriprep_dir}/${anat_suffix}/sub-0${trans_file_suffix}"] \
  -n NearestNeighbor \
  -o ${output_dir}/sub-0_thomasfull/sub-0_mni_right_${roi}
done

echo "ANTS transform for right thomasrfull complete."